# Copyright (c) 2025 ETH Zurich and University of Bologna
# SPDX-License-Identifier: Apache-2.0
---

manifest:
  self:
    path: sensei-sdk

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: sdk-nrf
      remote: ncs
      path: nrf
      revision: v2.6.1
      import: true
      west-commands: scripts/west-commands.yml
    - name: ubxlib
      url: https://github.com/u-blox/ubxlib.git
      path: modules/ubxlib
